version: "3.7"
services: 
  asesoria-academica:
  container_name: asesoria-academica
  image: mariaarenas/asesoria-academica:1.0.1
  build:
      dockerfile: asesoria-academica/Dockerfile
      context: .
  ports:
   - "4001:4001"
  networks:
   - ase-acad
networks:
  ase-acad: